import type { ToolRecord } from "@/types/content";

const tool = (
  id: string,
  category: ToolRecord["category"],
  slug: string,
  title: string,
  description: string,
  status: ToolRecord["status"] = "planned",
  relatedToolIds: string[] = [],
): ToolRecord => ({
  id,
  category,
  slug,
  title: { en: title },
  description: { en: description },
  status,
  relatedToolIds,
});

export const tools: ToolRecord[] = [
  tool(
    "pdf-compressor",
    "pdf",
    "pdf-compressor",
    "PDF Compressor",
    "Reduce PDF file size while keeping documents readable.",
  ),
  tool(
    "pdf-merger",
    "pdf",
    "pdf-merger",
    "PDF Merger",
    "Combine multiple PDF files in the order you choose.",
    "published",
    ["image-compressor"],
  ),
  tool(
    "pdf-splitter",
    "pdf",
    "pdf-splitter",
    "PDF Splitter",
    "Split a PDF into smaller documents.",
  ),
  tool(
    "pdf-to-jpg",
    "pdf",
    "pdf-to-jpg",
    "PDF to JPG",
    "Turn PDF pages into JPG images.",
  ),
  tool(
    "jpg-to-pdf",
    "pdf",
    "jpg-to-pdf",
    "JPG to PDF",
    "Combine JPG images into a PDF.",
  ),
  tool(
    "pdf-page-extractor",
    "pdf",
    "pdf-page-extractor",
    "PDF Page Extractor",
    "Save selected pages from a PDF.",
  ),
  tool(
    "image-compressor",
    "image",
    "image-compressor",
    "Image Compressor",
    "Make JPEG, PNG and WebP images smaller.",
    "published",
    ["pdf-merger"],
  ),
  tool(
    "image-resizer",
    "image",
    "image-resizer",
    "Image Resizer",
    "Resize images to exact dimensions.",
  ),
  tool(
    "jpg-to-png",
    "image",
    "jpg-to-png",
    "JPG to PNG",
    "Convert JPG images to PNG.",
  ),
  tool(
    "png-to-jpg",
    "image",
    "png-to-jpg",
    "PNG to JPG",
    "Convert PNG images to JPG.",
  ),
  tool(
    "word-counter",
    "text",
    "word-counter",
    "Word Counter",
    "Count words, characters, sentences and reading time.",
    "published",
    ["json-formatter"],
  ),
  tool(
    "character-counter",
    "text",
    "character-counter",
    "Character Counter",
    "Count characters with or without spaces.",
  ),
  tool(
    "case-converter",
    "text",
    "case-converter",
    "Case Converter",
    "Change text between common letter cases.",
  ),
  tool(
    "remove-duplicate-lines",
    "text",
    "remove-duplicate-lines",
    "Remove Duplicate Lines",
    "Remove repeated lines from text.",
  ),
  tool(
    "url-encoder-decoder",
    "web",
    "url-encoder-decoder",
    "URL Encoder / Decoder",
    "Encode or decode URL text safely.",
  ),
  tool(
    "json-formatter",
    "web",
    "json-formatter-validator",
    "JSON Formatter / Validator",
    "Format, minify and validate JSON.",
    "published",
    ["word-counter", "qr-generator"],
  ),
  tool(
    "qr-generator",
    "web",
    "qr-code-generator",
    "QR Code Generator",
    "Create downloadable QR codes locally.",
    "published",
    ["json-formatter"],
  ),
  tool(
    "qr-barcode-scanner",
    "scanner",
    "qr-barcode-scanner",
    "QR / Barcode Scanner",
    "Read supported codes from images.",
  ),
  tool(
    "website-screenshot",
    "scanner",
    "website-screenshot",
    "Website Screenshot Tool",
    "Capture a public webpage as an image.",
  ),
  tool(
    "website-metadata",
    "scanner",
    "website-metadata-checker",
    "Website Metadata Checker",
    "Inspect public webpage metadata.",
  ),
];
