import type { ToolRecord } from "@/types/content";

const tool = (
  id: string,
  category: ToolRecord["category"],
  slug: string,
  title: string,
  description: string,
  status: ToolRecord["status"] = "planned",
  relatedToolIds: string[] = [],
): ToolRecord => ({
  id,
  category,
  slug,
  title: { en: title },
  description: { en: description },
  status,
  relatedToolIds,
});

export const tools: ToolRecord[] = [
  tool(
    "youtube-video-to-audio",
    "web",
    "youtube-video-to-audio",
    "YouTube to MP3 – Video to Audio",
    "Explore YouTube audio downloads and our MP3 converter preview. Online conversion coming soon.",
    "published",
  ),
  tool(
    "pdf-compressor",
    "pdf",
    "pdf-compressor",
    "PDF Compressor",
    "Reduce PDF file size while keeping documents readable.",
  ),
  tool(
    "pdf-merger",
    "pdf",
    "pdf-merger",
    "PDF Merger",
    "Combine multiple PDF files in the order you choose.",
    "published",
    ["image-compressor"],
  ),
  tool(
    "pdf-splitter",
    "pdf",
    "pdf-splitter",
    "PDF Splitter",
    "Split a PDF into smaller documents.",
  ),
  tool(
    "pdf-to-jpg",
    "pdf",
    "pdf-to-jpg",
    "PDF to JPG",
    "Turn PDF pages into JPG images.",
  ),
  tool(
    "jpg-to-pdf",
    "pdf",
    "jpg-to-pdf",
    "JPG to PDF",
    "Combine JPG images into a PDF.",
  ),
  tool(
    "pdf-page-extractor",
    "pdf",
    "pdf-page-extractor",
    "PDF Page Extractor",
    "Save selected pages from a PDF.",
  ),
  tool(
    "image-compressor",
    "image",
    "image-compressor",
    "Image Compressor",
    "Make JPEG, PNG and WebP images smaller.",
    "published",
    ["pdf-merger"],
  ),
  tool(
    "image-resizer",
    "image",
    "image-resizer",
    "Image Resizer",
    "Resize images to exact dimensions.",
  ),
  tool(
    "jpg-to-png",
    "image",
    "jpg-to-png",
    "JPG to PNG",
    "Convert JPG images to PNG.",
  ),
  tool(
    "png-to-jpg",
    "image",
    "png-to-jpg",
    "PNG to JPG",
    "Convert PNG images to JPG.",
  ),
  tool(
    "word-counter",
    "text",
    "word-counter",
    "Word Counter",
    "Count words, characters, sentences and reading time.",
    "published",
    ["json-formatter"],
  ),
  tool(
    "character-counter",
    "text",
    "character-counter",
    "Character Counter",
    "Count characters with or without spaces.",
  ),
  tool(
    "case-converter",
    "text",
    "case-converter",
    "Case Converter",
    "Convert text to uppercase, lowercase, title or sentence case.",
    "published",
    ["word-counter", "whitespace-cleaner"],
  ),
  tool(
    "remove-duplicate-lines",
    "text",
    "remove-duplicate-lines",
    "Remove Duplicate Lines",
    "Remove repeated lines while preserving their first occurrence.",
    "published",
    ["text-sorter", "whitespace-cleaner"],
  ),
  tool(
    "url-encoder-decoder",
    "web",
    "url-encoder-decoder",
    "URL Encoder / Decoder",
    "Encode or decode URL components safely in your browser.",
    "published",
    ["base64-encoder-decoder"],
  ),
  tool(
    "json-formatter",
    "web",
    "json-formatter-validator",
    "JSON Formatter / Validator",
    "Format, minify and validate JSON.",
    "published",
    ["word-counter", "qr-generator"],
  ),
  tool(
    "qr-generator",
    "web",
    "qr-code-generator",
    "QR Code Generator",
    "Create downloadable QR codes locally.",
    "published",
    ["json-formatter"],
  ),
  tool(
    "qr-barcode-scanner",
    "scanner",
    "qr-barcode-scanner",
    "QR / Barcode Scanner",
    "Read supported codes from images.",
  ),
  tool(
    "website-screenshot",
    "scanner",
    "website-screenshot",
    "Website Screenshot Tool",
    "Capture a public webpage as an image.",
  ),
  tool(
    "website-metadata",
    "scanner",
    "website-metadata-checker",
    "Website Metadata Checker",
    "Inspect public webpage metadata.",
  ),
  tool(
    "age-calculator",
    "calculators",
    "age-calculator",
    "Age Calculator",
    "Calculate your exact age in years, months and days.",
    "published",
    ["date-difference-calculator", "bmi-calculator"],
  ),
  tool(
    "bmi-calculator",
    "calculators",
    "bmi-calculator",
    "BMI Calculator",
    "Estimate body mass index from height and weight.",
    "published",
    ["age-calculator"],
  ),
  tool(
    "percentage-calculator",
    "calculators",
    "percentage-calculator",
    "Percentage Calculator",
    "Find what percentage one number is of another.",
    "published",
    ["discount-calculator", "gst-calculator"],
  ),
  tool(
    "discount-calculator",
    "calculators",
    "discount-calculator",
    "Discount Calculator",
    "Calculate sale price and savings instantly.",
    "published",
    ["percentage-calculator", "gst-calculator"],
  ),
  tool(
    "gst-calculator",
    "calculators",
    "gst-calculator",
    "GST Calculator",
    "Add or extract Indian GST from an amount.",
    "published",
    ["discount-calculator", "emi-calculator"],
  ),
  tool(
    "emi-calculator",
    "calculators",
    "emi-calculator",
    "EMI Calculator",
    "Estimate monthly loan EMI from amount, rate and tenure.",
    "published",
    ["sip-calculator", "gst-calculator"],
  ),
  tool(
    "sip-calculator",
    "calculators",
    "sip-calculator",
    "SIP Calculator",
    "Estimate future value of monthly SIP investments.",
    "published",
    ["emi-calculator"],
  ),
  tool(
    "date-difference-calculator",
    "calculators",
    "date-difference-calculator",
    "Date Difference Calculator",
    "Count the days between any two dates.",
    "published",
    ["age-calculator"],
  ),
  tool(
    "unit-converter",
    "calculators",
    "unit-converter",
    "Length Unit Converter",
    "Convert kilometres, metres, feet, inches and more.",
    "published",
    ["fuel-cost-calculator"],
  ),
  tool(
    "fuel-cost-calculator",
    "calculators",
    "fuel-cost-calculator",
    "Fuel Cost Calculator",
    "Estimate trip fuel cost from distance and mileage.",
    "published",
    ["unit-converter"],
  ),
  tool(
    "text-sorter",
    "text",
    "text-sorter",
    "Text Sorter",
    "Sort lines alphabetically in your browser.",
    "published",
    ["remove-duplicate-lines"],
  ),
  tool(
    "find-replace-text",
    "text",
    "find-replace-text",
    "Find and Replace Text",
    "Replace every matching phrase in a block of text.",
    "published",
    ["case-converter"],
  ),
  tool(
    "whitespace-cleaner",
    "text",
    "whitespace-cleaner",
    "Whitespace Cleaner",
    "Remove extra spaces and blank lines from text.",
    "published",
    ["case-converter", "line-counter"],
  ),
  tool(
    "line-counter",
    "text",
    "line-counter",
    "Line Counter",
    "Count lines and characters as you type.",
    "published",
    ["word-counter"],
  ),
  tool(
    "base64-encoder-decoder",
    "web",
    "base64-encoder-decoder",
    "Base64 Encoder / Decoder",
    "Encode text as Base64 or decode it locally.",
    "published",
    ["url-encoder-decoder"],
  ),
  tool(
    "password-generator",
    "web",
    "password-generator",
    "Secure Password Generator",
    "Generate a strong random password on your device.",
    "published",
    ["uuid-generator"],
  ),
  tool(
    "uuid-generator",
    "web",
    "uuid-generator",
    "UUID Generator",
    "Generate a random RFC 4122 UUID in your browser.",
    "published",
    ["password-generator"],
  ),
];
